apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: rielu-site3
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "rielu-site3"
      images:
        - alias: "rielu-site3"
          imageName: "registry.uniproject.jp/rielu-site3/rielu-site3"
