apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: rielu-homepage2-site
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "rielu-homepage2-site"
      images:
        - alias: "rielu-homepage2-site"
          imageName: "registry.rielu-homepage2/official/rielu-homepage2-site"
          commonUpdateSettings:
            updateStrategy: "semver"
