apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: rielu-site3
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "rielu-site3"
      images:
        - alias: "rielu-site3"
<<<<<<< HEAD
          imageName: "registry.uniproject.jp/official/rielu-site3"
          commonUpdateSettings:
            updateStrategy: "semver"
=======
          imageName: "registry.uniproject.jp/rielu-site3/rielu-site3"
>>>>>>> a22570f6e304e9b5e8192c688edd2aae8c22031c
